nix-community/nixd

lib/lspserver/include/lspserver/DraftStore.h
lib/lspserver/include/lspserver/Path.h
lib/lspserver/include/lspserver/SourceCode.h
lib/lspserver/meson.build
lib/lspserver/src/DraftStore.cpp
lib/lspserver/src/SourceCode.cpp
lib/nixd/include/nixd/Server.h
lib/nixd/src/Server.cpp

Implemented text document sync methods, incrementally sync the textDocument. The implementation is picked from [clangd](https://github.com/llvm/llvm-project/blob/63eb04a3683996db26dbf1534682c5696d93b080/clang-tools-extra/clangd/SourceCode.cpp#L149).

lspserver: document sync framework

---

.github/workflows/build.yml
flake.nix
meson.build
meson.options

This is required for nix headers, to make sure that they provide the same declaration as the compiled library.

build-system: include nix/config.h in all translation units.

---

lib/nixd/src/Server.cpp
lib/nixd/test/server.cpp

fix basePath bug and add unit test about it.
Fixes #8

Fix basePath is full path instead of directory

---

lib/nixd/src/Diagnostic.cpp
lib/nixd/src/Server.cpp
lib/nixd/test/server.cpp

`ASSERT_TRUE(SRO.contains(R"("whatEverUndefined)"));` can not pass not because ansi but the redundant `"`, so I remove the comment.
the reason why I not add unit test is that I can not find ANSI code in the output of `SRO.str()` and `Diagnostics[0].message`
Fixes: #10

nixd: emove nix ANSI color but not add unit test

---

lib/nixd/include/nixd/CallbackExpr.h
lib/nixd/meson.build
lib/nixd/src/CallbackExpr.cpp
lib/nixd/test/expr.cpp

This allow us rewritting AST nodes with injected "Callback" on evaluating. Rewritting pattern are generated by macros (with a lot of magic).

nixd: callback expressions support

---

meson.build
tools/nix-ast-dump/nix-ast-dump.cpp
tools/nix-ast-dump/test/all-grammar.nix
tools/nix-ast-dump/test/lit.cfg.py

also add an ast dump utility, produces indented output:
```console
[user@system]$ build/nix-ast-dump ~flakes/shell.nix
ExprLambda: ({ pkgs ? (let lock = (((builtins).fromJSON ((builtins).readFile ~flakes/flake.lock))).nodes.nixpkgs.locked; nixpkgs = (fetchTarball { sha256 = (lock).narHash; url = ("https://github.com/nixos/nixpkgs/archive/" + (lock).rev + ".tar.gz"); }); in (import nixpkgs { overlays = [ ]; })), ... }: ((pkgs).mkShell { NIX_CONFIG = "extra-experimental-features = nix-command flakes repl-flake"; nativeBuildInputs = (with pkgs; [ (nix) (home-manager) (git) (sops) (gnupg) (age) ]); }))
ExprLet: (let lock = (((builtins).fromJSON ((builtins).readFile ~flakes/flake.lock))).nodes.nixpkgs.locked; nixpkgs = (fetchTarball { sha256 = (lock).narHash; url = …
```

tools: add `nix-ast-dump`

---

lib/nixd/include/nixd/EvalDraftStore.h
lib/nixd/meson.build
lib/nixd/src/EvalDraftStore.cpp
lib/nixd/test/evalDraftStore.cpp

Class for virtual workspace evaluation & injection. LSP clients should `addDraft` in this store, and call `withEvaluation`, write logics in the callback.

nixd/eval: add EvalDraftStore

---

tools/nixd/test/basic-diagnostic.md
tools/nixd/test/initialize.md
tools/nixd/test/workspace-configuration-no-client-cap.md
tools/nixd/test/workspace-configuration.md

Fixes: #32 
Fixed a mistake where the arrow was not facing the same direction as the other arrows in the rest of the file.

nixd/regression: fixed arrow direction

---

flake.nix

`clangd` provided by llvmPackages is unwrapped, and do not respect env:
$NIX_CFLAGS_COMPILE
However this is critical for clangd to find headers, so let's add this workaround.

flake: add shellHook in devShell to ensure clangd is wrapped

---

lib/nixd/src/EvalDraftStore.cpp

... This will dramatically affect our speed on responding requests.
However, we have to do this, because nix evaluation is NOT thread-safe.

nixd/eval: put this stuff in main thread

---

flake.nix

add overlay support
```nix 
{
description = "My configuration";
inputs = {
nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
nixd.url = "github:nix-community/nixd";
};
outputs = { nixpkgs, nixd, ... }:
{
nixosConfigurations = {
hostname = nixpkgs.lib.nixosSystem
{
system = "x86_64-linux";
modules = [
{
nixpkgs.overlays = [ nixd.overlays.default ];
environment.systemPackages = with pkgs;[
nixd
];
}
];
};
};
};
}
```

flake: add nixd overlay (providing the `nixd` package)

---

lib/nixd/include/nixd/nix/EvalState.h
lib/nixd/meson.build
lib/nixd/src/nix/EvalState.cpp

This is a helper function (and could be upstreamed) that can specify a depth limit in `nix::EvalState::forceValue`, which allows our user to configure the installable with additional eval depth (and thus their structs in ExprAttrs will be evaluated.)

nixd/nix: add nix extension `forceValueDepth` to `nix::EvalState`

---

lib/nixd/include/nixd/Server.h
lib/nixd/src/ServerController.cpp
lib/nixd/src/ServerWorker.cpp

This will send a diagnostic message to the client after the evaluation finished. Might be helpful if the user is preparing a package/NixOS module.
Fixes: #69

nixd/diagnostic: send evaluation diagnostic to client

---

flake.lock
lib/nixd/src/AST.cpp
lib/nixd/src/EvalDraftStore.cpp
lib/nixd/test/ast.cpp
lib/nixd/test/diagnostic.cpp
lib/nixd/test/expr.cpp
tools/nix-ast-dump/nix-ast-dump.cpp

The breaking change is: we have to use nix::CanonPath() to wrap around paths.

flake: bump nix to 2.16.0

---

docs/user-guide.md
lib/nixd/include/nixd/EvalDraftStore.h
lib/nixd/include/nixd/JSONSerialization.h
lib/nixd/include/nixd/Server.h
lib/nixd/include/nixd/nix/Option.h
lib/nixd/include/nixd/nix/Value.h
lib/nixd/meson.build
lib/nixd/src/JSONSerialization.cpp
lib/nixd/src/ServerController.cpp
lib/nixd/src/ServerWorker.cpp
lib/nixd/src/nix/Option.cpp
lib/nixd/src/nix/Value.cpp
tools/nixd/test/workspace-configuration-eval-depth.md

Fixes: #87
TODO:
Tested home-manager & nixos options:

nixd/completion/options: natively support all kinds of nixpkgs options

---

lib/lspserver/include/lspserver/Logger.h
lib/lspserver/src/Logger.cpp

This will release the lock to avoid deadlocks on crashed program.

lspserver: remove the named mutex when logger startup

---

lib/nixd/include/nixd/nix/Value.h
lib/nixd/src/ServerWorker.cpp
lib/nixd/src/nix/Value.cpp
tools/nixd/test/goto-definition-derivation.md

Fixes: #112
This is a cool feature that brings you to the position where a package defined.

nixd: goto definition for derivations

---

lib/nixd/src/ServerWorker.cpp

Fixes: #116
Inspired-by: https://github.com/oxalica/nil/issues/9#issuecomment-1311972565
Actually the current impl is just do the comment. However we do not need to start repl or whatever.

nixd/definition: goto definition for any evaluated non-pos-discarded values

---

editors/nvim-lsp.nix

When the cursor is moved to the problematic line the diagnostic information will be displayed as a floating window

editors/nvim-lsp: fix don't display diagnostic information

---

lib/lspserver/include/lspserver/Logger.h
lib/lspserver/src/Logger.cpp

This gurantees that the owner will release the lock if it is died (which is a fairly common case in nixd, because we are actively killing workers).

lspserver/logger: use lowlevel robust lock

---

lib/nixd/src/ServerEval.cpp

This will be useful if you are typing `with` expressions.
e.g.
```nix
with foo; [
]
```

nixd: search "ContainMin" instead of "Start" for completion

---

lib/nixd/include/nixd/AST.h
lib/nixd/include/nixd/JSONSerialization.h
lib/nixd/include/nixd/Server.h
lib/nixd/src/JSONSerialization.cpp
lib/nixd/src/ServerController.cpp
lib/nixd/src/ServerEval.cpp
tools/nixd/test/initialize.md

This is currently not testable, because nix will try to lstat the path.
Fixes: #138

nixd/documentLink: init

---

lib/nixd/include/nixd/nix/Value.h
lib/nixd/src/ServerEval.cpp
lib/nixd/src/nix/Value.cpp

Large prints make our worker busy and sometimes unnecessary.

nixd: override upstream `nix::Value::print` to get shorter message

---

lib/nixd/include/nixd/Diagnostic.h
lib/nixd/src/Diagnostic.cpp
lib/nixd/src/ServerEval.cpp

Cherry-picks:
6858a5e (nixd/diagnostic: improve diagnostic for multi-errors, 2023-06-26)
Aiming at providing more diagnostics on a single file, instead of sending it multiple times (LSP client will only show the latest in this case).

nixd/diagnostic: improve for multiple errors on single file

---

lib/nixd/include/nixd/nix/ParserEpilogue.cpp
lib/nixd/include/nixd/nix/ParserPrologue.h
lib/nixd/include/nixd/nix/ParserRequire.h

Tested on many large workloads:
```
❯ valgrind --leak-check=full build/nixd-ast-dump ../nixpkgs/lib/deprecated.nix
==4119151== Memcheck, a memory error detector
==4119151== Copyright (C) 2002-2022, and GNU GPL'd, by Julian Seward et al.
==4119151== Using Valgrind-3.21.0 and LibVEX; rerun with -h for copyright info
==4119151== Command: build/nixd-ast-dump ../nixpkgs/lib/deprecated.nix
==4119151==
==4119151==
==4119151== HEAP SUMMARY:
==4119151==     in use at exit: 159,477 bytes in 2,313 blocks
==4119151==   total heap usage: 18,151 allocs, 15,838 frees, 1,558,447 bytes allocated
==4119151==
==4119151== LEAK SUMMARY:
==4119151==    definitely lost: 0 bytes in 0 blocks
==4119151==    indirectly lost: 0 bytes in 0 blocks
==4119151==      possibly lost: 0 bytes in 0 blocks
==4119151== …
```

nixd/parser: make the parser memory-safe

---

nixd/tools/nixd/nixd.cpp

Use the system call prctl to inform OS killing all forked processes after the parent died.

nixd: kill child on linux

---

docs/user-guide.md

Correct “writting” to “writing”.

docs/user-guide: typo fix, “writting” -> “writing”

---

nixd/include/nixd/Server/ASTManager.h
nixd/include/nixd/Server/Server.h
nixd/lib/Server/ASTManager.cpp
nixd/lib/Server/Controller.cpp

Fixes the error found in the CI:
https://github.com/nix-community/nixd/actions/runs/5474230815
If the new version haven't been evaluated, but enqueued, wait for the new version, do not process the old one.

nixd/Server: fix outdated draft version for static analysis

---

nixd/include/nixd/Sema/CompletionBuilder.h
nixd/lib/Sema/CompletionBuilder.cpp
nixd/lib/Server/EvalWorker.cpp

nixd/Sema: filter item prefix for completion builder

---

nixd/lib/Server/Controller.cpp

Previously, when `workspace/configuration` was unset, we would get `[null]`, causing an error to be raised by LLVM. While this error is harmless, it causes confusion (it is mentioned in #266, for example). This PR replaces the error message with a log that mentions `workspace/configuration` is unset. This should be more informative for users using `.nixd.json` instead of `workspace/configuration` to configure nixd.

nixd/Server/configuration: Log when `workspace/configuration` is `[null]`

---

docs/editor-setup.md

Adds a section to [editor-setup.md](https://github.com/nix-community/nixd/blob/main/docs/editor-setup.md) that adds guidance on making nixd work with Emacs. When https://github.com/emacs-lsp/lsp-mode/pull/4125 (or another PR that adds nixd) is merged, this section should be changed.

docs/editor-setup: add Emacs setup information

---

.github/workflows/update-flake-lock.yml

This daily tests if nixpkgs updates breaks our interface.

github/workflows: add update-flake-lock action to bump deps

---

libnixt/include/nixt/ArrayRef.h
libnixt/include/nixt/PtrPool.h
libnixt/include/nixt/Serialize.h
libnixt/lib/Deserialize.cpp
libnixt/lib/Serialize.cpp
libnixt/meson.build
libnixt/test/Deserialize.cpp
libnixt/test/Serialize.cpp

Add serialization method for incoming IPC design. This is a binary format using POD data structures.
Only a few trivial AST nodes has been implemented.

libnixt: add Serialize

---

libnixf/include/nixf/Parse/Nodes.h
libnixf/lib/Parse/Lexer.cpp
libnixf/lib/Parse/Parser.cpp
libnixf/lib/Parse/Token.h
libnixf/lib/Parse/test/Parser.cpp

`StringParts` are different from path fragments because paths have no *surrounding quotes*. So, the first path fragment should be parsed normally, and the rest in "PS_Path" context. Previously `parseInterpolableParts` was used for only unified parsing contexts (and this only works for strings). So it was renamed to `parseStringParts`.

libnixf: parse ExprPath

---

nixd/docs/nixd-schema.json
nixd/docs/user-guide.md

Fix #222
1. Create a json schema
2. Add its URL to schemastore.
Now the json schema is added to this repo. I'll send a PR to add the URL of this json schema to [schema store](https://github.com/SchemaStore/schemastore)

nixd: add a json schema

---

nixd/docs/editor-setup.md

was setting this up myself, so figured others could benefit :)

docs/editor-setup: extend Emacs setup to include Eglot

---

nixd/include/nixd/CommandLine/Options.h
nixd/include/nixd/Controller/Controller.h
nixd/lib/CommandLine/Options.cpp
nixd/lib/Controller/LifeTime.cpp
nixd/lib/Controller/Support.cpp
nixd/tools/nixd-attrset-eval.cpp
nixd/tools/nixd.cpp
nixd/tools/nixd/test/completion-nixpkgs.md

To speed up lit-testing, we don't need to evaluate full nixpkgs.

nixd: use orphan nixpkgs, nixos default in lit-test mode

---

libnixf/src/Parse/Lexer.cpp

While bumping my system flake I ran into a test failing due to an out-of-bounds access. It got caught by `_GLIBCXX_ASSERTIONS`. I guess the not-so-recent [bump](https://www.github.com/NixOS/nixpkgs/pull/298047) of meson in nixpkgs brought in this [commit](https://www.github.com/mesonbuild/meson/pull/12683) from meson 1.4.0.
Here's the failing test logs and a backtrace:
```bash
nixd-nightly> >>> MALLOC_PERTURB_=222 LD_LIBRARY_PATH=/build/3gwj8jwd4ypvcahxqv3cn2fq617fm7v2-source/build/libnixbc:/build/3gwj8jwd4ypvcahxqv3cn2fq617fm7v2-source/build/libnixf:/build/3gwj8jwd4ypvcahxqv3cn2fq617fm7v2-source/build/libbc ASAN_OPTIONS=halt_on_error=1:abort_on_error=1:print_summary=1 UBSAN_OPTIONS=halt_on_error=1:abort_on_error=1:print_summary=1:print_stacktrace=1 …
```

libnixf: fix out-of-bounds access in `Lexer::consumeManyOf`

---

flake.lock

https://github.com/nix-community/nixd/pull/443 mentioned meson updates with assertion enabled caught some out-of-bounds violation in our lexer, bump flake version to make sure it is coveraged in our CI.

flake: update the lock

---

libnixf/include/nixf/Basic/DiagnosticKinds.inc
libnixf/include/nixf/Basic/NoteKinds.inc
libnixf/src/Sema/VariableLookup.cpp
libnixf/test/Sema/VariableLookup.cpp

Provide diagnostic mentioned in https://github.com/NixOS/nix/issues/490

libnixf: provide linting for escaping `with`

---

libnixt/include/nixt/Value.h
libnixt/lib/Value.cpp
nixd/lib/Eval/AttrSetProvider.cpp

Currently these options are nested under
`foo.bar.<name>.options`
Fixes: #106

{libnixt,nixd/Eval}: support `attrsOf submodule`

---

nixd/docs/features.md
nixd/lib/Controller/LifeTime.cpp

Recently @GaetanLepage reported these tokens looks very strange on some color theme, in vim.
Introduce a CLI flag that completely disable this feature at all. Because changing color theme might be non-trivial.

nixd: introduce `--semantic-tokens=true/false` to toggle the feature

---

libnixf/src/Sema/VariableLookup.cpp
libnixf/test/Sema/VariableLookup.cpp

libnixf/Sema: place `with` warning only on its keyword

---

nixd/docs/configuration.md

Here’s what the `debug.options` and `currentSystem.options` looks like in [services-flake’s dev flake](https://github.com/juspay/services-flake/tree/main/dev):
```sh
services-flake/dev on  main [!] via ❄️  impure (nix-shell-env) took 2m9s
❯ nix repl
Welcome to Nix 2.18.2. Type :? for help.
nix-repl> :lf .
warning: Git tree '/Users/shivaraj/oss/services-flake' is dirty
Added 23 variables.
nix-repl> currentSystem.options
{ _module = { ... }; allModuleArgs = { ... }; apps = { ... }; checks = { ... }; debug = { ... }; devShells = { ... }; flake-root = { ... }; formatter = { ... }; legacyPackages = { ... }; packages = { ... }; pre-commit = { ... }; treefmt = { ... }; }
nix-repl> debug.options
{ _module = { ... }; allSystems = { ... }; debug = { ... }; flake = { ... }; perInput = { ... }; …
```

docs(configuration): Add configuration for a `perSystem` flake-parts option

---

libnixf/include/nixf/Basic/Nodes/Simple.h
nixd/tools/nixd/test/diagnostic-liveness-path.md

Fixes: https://github.com/nix-community/nixd/issues/472

libnixf: fix missing visitor for `ExprPath`

---

default.nix

There are many Nix LSP servers, so let's use a description that's unique to nixd.
Note: this description is shown via LSP in VSCode:

pkg: add a non-generic description

---

libnixf/src/Sema/VariableLookup.cpp
libnixf/test/Sema/VariableLookup.cpp

Emtpy let ... in ... expression, leaving a nullptr in libnixf's "Let" struct, causes the code not continue visiting the body at all.
Fixes: #500

libnixf: fix variable lookup not visiting empty let ... in ... expr

---

libnixf/src/Parse/ParseSupport.cpp
libnixf/src/Parse/Parser.h
libnixf/test/Parse/ParseExpr.cpp

libnixf: report error if extra token is consumed

---

nixd/docs/configuration.md

This fixes some minor typos in the documentation.

nixd/docs: fix typos

---

libnixf/include/nixf/Basic/Nodes/Attrs.h
libnixf/include/nixf/Sema/SemaActions.h
libnixf/src/Sema/SemaActions.cpp
libnixf/src/Sema/VariableLookup.cpp
libnixf/test/Sema/SemaActions.cpp
libnixf/test/Sema/VariableLookup.cpp

Consider recursive attributes:
rec {
inherit (expr) attr;
inherit attr;
}
The syntax:
inherit (expr) attr
is desugared into
attr = expr.attr
.
The expression `expr.attr` should be evaluated in new environment, created by `rec` keyword
However,
inherit attr
desugaring to
attr = attr
should be evaluated in parent environment.
This scoping rule is somehow straightfoward but not really documented. libnixf previously evaluated the second case in "new environment".
Fixes: #513

libnixf/Sema: fix attribute source context of `inherit (expr) ...`

---

libnixf/include/nixf/Basic/DiagnosticKinds.inc

Didn't change the diagnostic ID, you should look into it yourself if necessary.

libnixf: clearer diagnostic message for escaping the `with` expression

---

libnixt/lib/Value.cpp

Trying to get completions from nixvim gets trouble, because all of its options are nested under a "submodule".
The PR adds basic support for mangling submodule options into it's declaration, and completion for nixvim works.
Fixes: #517

libnixt: mangle `submodule` options to it's declaration

---

nixd/lib/Controller/Definition.cpp
nixd/tools/nixd/test/definition-package.md

Nixpkgs meta.positions does not have any character information, only line numbers get retrieved.
Previously this number will be assigned with randomly, say, equals to line numbers.
This PR fixup that character number to zero as if there may be some rendering issue for neovim.
Fixes: #523

nixd/Controller: fix character number -> 0

---

nixd/lib/Controller/Hover.cpp
nixd/tools/nixd/test/hover-options.md

Closes #174
This patch implements hover documentation for options.

nixd/hover: hover documentation for options

---

libnixf/include/nixf/Basic/Diagnostic.h
libnixf/include/nixf/Basic/DiagnosticKinds.inc
nixd/lib/Controller/Convert.cpp
nixd/tools/nixd/test/diagnostic-liveness-formal.md

After this patch nixd won't be very chatty if some variable is not used. I think this is a better approach in comparison to marking a "warning". Unused variables are generally not very harmful in Nix codes, and indeed developers may rely on it. Thus the severity of all liveness related warnings are demoted to "hint".

libnixf,nixd: demote livenss warning severity to "hint"

---

libnixf/src/Sema/VariableLookup.cpp
libnixf/test/Sema/VariableLookup.cpp

Giving an "escaping with" warning to builtin variables like `true`, `false` or `null` is not very suitable:

libnixf: disable escaping `with` warning for builtin

---

libnixf/src/Sema/VariableLookup.cpp
libnixf/test/Sema/VariableLookup.cpp

let ... in ... expr may create pass-through environments to "emitLivenessWarning". However, this function does not consider the "builtin" scope. In this case, `Def->syntax()` will be nullptr and thus the server crashes.
Add the checking to "emitLivenessWarning" function.
Fixes: #533

libnixf/Sema: ignore builtin liveness warning

---

nixd/tools/nixd-attrset-eval/test/lit.cfg.py

nixd: don't pass `NIX_PATH` to nixd-attrset-eval unit tests

---

nixd/include/nixd/Protocol/AttrSet.h
nixd/lib/Controller/AST.cpp
nixd/lib/Controller/AST.h
nixd/lib/Controller/Completion.cpp
nixd/tools/nixd/test/completion-select-lib.md
nixd/tools/nixd/test/completion-select.md

nixd: `lib` + `pkgs` completion with "select", e.g. `lib.gen|`, `pkgs.stdenv.mkDerivat|`

---

nixd/tools/nixd/test/completion/pkgs.md

Dereferencing empty vector and thus crash.

nixd/test/completion: precommit `pkgs` failing test

---

nixd/lib/Controller/AST.cpp
nixd/lib/Controller/AST.h
nixd/lib/Controller/Completion.cpp
nixd/lib/Controller/Definition.cpp
nixd/lib/Controller/Definition.h
nixd/lib/Controller/DocumentHighlight.cpp
nixd/lib/Controller/FindReferences.cpp
nixd/lib/Controller/Rename.cpp
nixd/tools/nixd/test/definition/package.md
nixd/tools/nixd/test/definition/select-package-with.md
nixd/tools/nixd/test/definition/select-package.md
nixd/tools/nixd/test/rename/duplicated.md
nixd/tools/nixd/test/rename/with.md

Add "goto definition" support for select expressions, e.g.
```nix
with pkgs; [
nixVersions.nix
]
```
```nix
pkgs.stdenv.mkDerivation
```
These values are now "Ctrl + Click"-able to nixpkgs locations.

nixd/Controller: support "goto definition" for select expressions

---

libnixf/include/nixf/Sema/VariableLookup.h
libnixf/src/Sema/VariableLookup.cpp
libnixf/test/Sema/VariableLookup.cpp

Fixes https://github.com/nix-community/nixd/issues/560

libnixf/Sema: differentiate lambda argument with and without formals

---

nixd/lib/Controller/AST.cpp
nixd/lib/Controller/AST.h
nixd/lib/Controller/Completion.cpp
nixd/lib/Controller/Definition.cpp
nixd/tools/nixd/test/completion/with-expr-select.md

Fixes: #555
Add auto-completion code-snippet like this:
```nix
with pkgs.vimPlugins; [
|
]
```
i.e. with a "select" expression.

nixd/Controller: support completion for `pkgs.subpackages`

---

libnixf/src/Basic/diagnostic.py

Because if you don’t remove such unnecessary patterns in time, you may make subtle mistakes later

libnixf: change extra-{rec,with},escaping-with diagnostics to warning

---

nixd/include/nixd/CommandLine/Configuration.h
nixd/include/nixd/Support/Exception.h
nixd/include/nixd/Support/JSON.h
nixd/lib/CommandLine/Configuration.cpp
nixd/lib/Controller/LifeTime.cpp
nixd/lib/Support/JSON.cpp
nixd/lib/meson.build
nixd/tools/nixd/test/format/format.md
nixd/tools/nixd/test/format/nixfmt

Add a CLI flag `-config` used to set initial configuration. For editor clients which does not support workspace configuration, the flag could be used as a fallback.

nixd/Controller: allow setting initial configuration via CLI

---

nixd/include/nixd/Controller/Controller.h
nixd/include/nixd/Controller/NixTU.h
nixd/lib/Controller/CodeAction.cpp
nixd/lib/Controller/Configuration.cpp
nixd/lib/Controller/Convert.cpp
nixd/lib/Controller/Convert.h
nixd/lib/Controller/Definition.cpp
nixd/lib/Controller/Diagnostics.cpp
nixd/lib/Controller/DocumentHighlight.cpp
nixd/lib/Controller/DocumentLink.cpp
nixd/lib/Controller/DocumentSymbol.cpp
nixd/lib/Controller/FindReferences.cpp
nixd/lib/Controller/Hover.cpp
nixd/lib/Controller/InlayHints.cpp
nixd/lib/Controller/NixTU.cpp
nixd/lib/Controller/Rename.cpp
nixd/lib/Controller/SemanticTokens.cpp
nixd/lib/Controller/Support.cpp
nixd/tools/nixd/test/utf16.md

Handle LSP spec (UTF16) character length for locations.

nixd/Controller: handle UTF-16 code units for locations

---

nixd/lib/Controller/AST.h
nixd/lib/Controller/Definition.cpp
nixd/tools/nixd/test/definition/builtin.md

Previously the server will crash.

nixd/Controller: report error on `textDocument/definition` on builtins

---

libnixf/include/nixf/Basic/NoteKinds.inc
libnixf/src/Basic/diagnostic.py
libnixf/src/Sema/VariableLookup.cpp
libnixf/test/Sema/VariableLookup.cpp
nixd/docs/configuration.md

This diagnostic highlighted too much.
In some cases, people may use "let" expression to override something inside `with pkgs;`
If "escaping-with" is diagnosed, there is no good fix to workaround, without completely disable that diagnostic in configuration.
CC @Aleksanaa who previously worked on this.

libnixf: remove `sema-escaping-with` because it is too pedantic

---

nixd/docs/editors/nvim-lsp.nix

Add markdown to enable nixdocs shown in hover.
Closes #592

nixd/docs/editors: add markdown parsers in nvim-lsp

---

nixd/docs/editor-setup.md

Upstream recently renamed server_configurations -> configs

nixd/docs/editor-setup: fix lspconfig link

---

nixd/docs/features.md
nixd/lib/Controller/LifeTime.cpp
nixd/tools/nixd/test/semantic-tokens/initialize.md

Semantic tokens (current implementation) caused a lot of trouble for users.
The common reason is confusing attribute path coloring for "same" tokens.
i.e.
```nix
{
program.a = 1;
program.b = 2;
}
```
Those two "program"s are colored differently, (looks like a bug frankly).
So let's disable it for now, for UX improvement.
We can re-enable it later if we have a better implementation.
Link: https://github.com/nix-community/nixd/issues/573

nixd/lib/Controller: disable semantic tokens feature during init

---

nixd/lspserver/src/Connection.cpp

nixd/lspserver: fix high cpu on fd polling

---

libnixf/src/Parse/Lexer.cpp
libnixf/test/Parse/Lexer.cpp

libnixf/Parse: handle indented strings `''\` escape sequence

---

libnixf/src/Parse/ParseExpr.cpp
libnixf/test/Parse/ParseAttrs.cpp

Small DX adjustments:
- Parser distinguishes a little better formals from attrsets
- Completion are triggered when discovering options of an attrset ( no need to try and guess the first letter )
I had to remove a check for the latter, please review carefully !

fix(completion): correctly parse incomplete attrsets and provide completions

---

libnixf/src/meson.build

Without the change the build sometimes fails as:
```
@nix { "action": "setPhase", "phase": "buildPhase" }
build flags: -j16
[1/37] Generating src/DiagnosticEnum.h with a custom command
[2/37] Generating src/Diagnostic.cpp with a custom command
[3/37] Compiling C++ object test/unit-libnixf-parse.p/Parse_ParseAttrs.cpp.o
FAILED: test/unit-libnixf-parse.p/Parse_ParseAttrs.cpp.o
g++ -Itest/unit-libnixf-parse.p -Itest -I../test -I../src/Parse -I../include -Isrc -I/nix/store/lb7qkwdmj8wms2df787npi93ackz5lll-boost-1.87.0-dev/include -I/nix/store/bfgjwkcb8snkizx578rzdahi75m8zyh4-nlohmann_json-3.11.3/include -I/nix/store/212jw2z087s4wy7jpivr47qk9h5wrbmv-gtest-1.16.0-dev/include -fdiagnostics-color=always -D_GLIBCXX_ASSERTIONS=1 -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=gnu++20 -O3 …
```

nixf: declare Tokens.h dependency for libnixf

---

nixd/lib/Controller/AST.cpp
nixd/lib/Controller/AST.h
nixd/lib/Controller/Completion.cpp
nixd/lib/Controller/Definition.cpp
nixd/lib/Controller/Hover.cpp
nixd/tools/nixd/test/completion/options-in-config.md
nixd/tools/nixd/test/hover/options-in-config.md

In NixOS modules options can be defined at the top-level, e.g:
{ foo = true; }
or inside of `config`, e.g:
{ config = { foo = true; }; }
Autocompletion and hover information before only worked for the former because the option resolving code had no special handling for `config`.
Fixes #566.

nixd: enable completion and hover in config sets

---

nixd/docs/configuration.md

Fixes: https://github.com/nix-community/nixd/issues/626

nixd/docs: document how to setup Home-manager installed as NixOS module

---

nixd/docs/editor-setup.md

Added simple example to setup KDE Kate editor, using the supported  LSP Client Plugin. Also added a link to the LSP Client Plugin documentation site for KDE and an example for the settings file path.

docs/editor-setup.md: add kate editor

---

nixd/lib/Controller/Support.cpp

Fixes the issue described in comment https://github.com/nix-community/vscode-nix-ide/issues/497#issuecomment-3316236257.

nixd/Controller: clear diagnostics when removing document
